import { useContext, useState } from "react";
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import useTranslation from 'next-translate/useTranslation';

import AppContext from "../AppContext";
import ContactModal from "../components/contactModal";

export default function Home() {
  const router = useRouter();
  const { t } = useTranslation();
  const [context, setContext] = useContext(AppContext);

  const toggleModal = () => {
    const modalOpened = context && context.isContactModalOpened;
    setContext({...context, isContactModalOpened: !modalOpened});
  };

  return (
    <>
      <Head>
        <title>{t('home:seo_title')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <header>
      <div className="row">
        <div className="col-6">
          <Image src="/logo.svg" alt="Logo" className="header-logo" width={80} height={80} />
        </div>
        <div className="col-6 header-languages">
          <ul>
            {router.locales.map(locale => (
              <li key={locale}>
                <Link href={router.asPath} locale={locale}>
                  <a>{locale}</a>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>
     </header>
     <div className="content d-flex flex-column align-items-center justify-content-center">
        <h1>{t('home:title')}</h1>
        <h2>{t('home:description')}</h2>
        <div onClick={toggleModal} className="button" href="mailto:gabriela@rosasconservation.com">
          <p className="button-text">
            {t('home:contact')}
          </p>
          <div className="button-icon-container">
            <p className="button-icon fa-solid fa-envelope"></p>
          </div>
        </div>
        <ContactModal />
      </div>
    </>
  )
}
